[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
redirect_stderr=true

[program:octane]
user=root
autostart=1
autorestart=1
numprocs=1
command=/usr/local/bin/frankenphp run --config /var/www/html/Caddyfile
directory=/var/www/html
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/octane.log
stopwaitsecs=10

[program:worker]
user=root
autostart=1
autorestart=1
numprocs=1
command=/usr/local/bin/frankenphp php-cli /var/www/html/artisan horizon
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/worker.log
stopwaitsecs=3600

[program:websocket]
user=root
autostart=1
autorestart=1
numprocs=1
command=/usr/local/bin/frankenphp php-cli /var/www/html/artisan ws:serve
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/websocket.log
